WIP: PO Änderungen Informatik
FachschaftMathPhysInfo/Ersti-Info pull request #374
Opened 2021-09-02 08:45 UTC by christian-heusel

Files to be edited:
- [x] `studiengaenge/bachelor_informatik.tex`
- [x] `studiengaenge/lehramt_info.tex `
- [x] `wie-geht-studium/vorlesungen_info.tex`
- [x] `wie-geht-studium/vorlesung_allgemein.tex`
- [x] `wie-geht-studium/seminar.tex`

Maybe this PR could also use external reviewers (dean of studies etc.)

2021-09-06 13:44 UTC, TomTomRixRix commented
We also might want to add @JasminMangei as a reviewer for the Lehramt-related topics

2021-09-06 13:46 UTC, christian-heusel commented
Also note that you can hide whitespace changes which makes reviewing this changeset way easier ^^
(just click on the ⚙️ > Check ✅ "Hide Whitespace Changes")

2021-09-06 20:43 UTC, TomTomRixRix commented on studiengaenge/bachelor_informatik.tex
> +\paragraph*{Im Bachelorseminar} erklärt ihr jeweils den anderen Studis in einem Vortrag ein euch zuvor zugeteiltes Thema aus einem zusammenhängenden Themenbereich. Was die tatsächliche Schwerpunktset
Vorschlag: variiert aber von Dozentin zu Dozentin? Lehrkraft klingt wirklich ein bisschen wie Schule und ist so langweilig genderneutral, da könnte man das generische Femininum mal wieder unterbringen

2021-09-06 20:58 UTC, TomTomRixRix commented on studiengaenge/bachelor_informatik.tex
> +Danach hört ihr im Modul \vl{Mathematische Grundlagen 3} eines der beiden Module \vl{Einführung in die Numerik} (\gls{Num0}) oder \vl{Einführung in die Wahrscheinlichkeitstheorie und Statistik} (\gls
Ich gehe mal davon aus, dass die Übergangsregelung nicht mehr für die neue PO gelten wird (auch wenn das meines Wissens nirgendwo festgelegt wurde). Jedenfalls wurde sie damals eingeführt, weil die Matheveranstaltungen des Wahlpflichtmoduls nicht regelmäßig angeboten werden konnten aus personellen Gründen. Da dies jedoch nicht mehr der Fall ist, ist es fraglich, ob die Übergangsregelung weitergeführt wird.

2021-09-06 21:03 UTC, TomTomRixRix commented on studiengaenge/lehramt_info.tex
> +Im zweiten Semester ist es vorteilhaft, \vl{Algorithmen und Datenstrukturen} (\gls{AlDa}) zu besuchen, da diese Vorlesung Grundlage für weitere Vorlesungen sein kann.
Bei der aktuellen AlDa empfiehlt es sich tatsächlich, vielleicht erst IBN zu belegen im zweiten Semester oder Datenbanken und AlDa dann nach der Mathevorlesung. Laut neuer PO werden IBN und AlDa empfohlen für das 2. Semester, aber ich würde mich Jasmin anschließen und Datenbanken und IBN oder ggf. sogar das Zweitfach einfach zuerst belegen. Außer man hat Mathematik als Zweitfach oder ein Mathemodul im ersten Semester belegt, dann kann man AlDa schon im zweiten belegen.

2021-09-06 21:07 UTC, TomTomRixRix commented on studiengaenge/lehramt_info.tex
> +% Studiert ihr den 50\%-Bachelor ohne Lehramtsoption, dann könnt ihr stattdessen ein \vl{Proseminar} und ein \vl{Anfängerpraktikum}, welche 6 Leistungspunkte „Fächerübergreifende Kompetenzen“ (FÜK) b
Wie Jasmin geschrieben hat, bietet sich jetzt das Anfängerpraktikum an mit 2 fachlichen und 4 FÜK Leistungspunkten.

2021-09-06 21:09 UTC, TomTomRixRix commented on studiengaenge/lehramt_info.tex
> +In Informatik solltet ihr euch bei jeder Veranstaltung genau darüber informieren, was ihr benötigt, um zur Prüfung zugelassen zu werden (z.B. 60\% auf den Übungszetteln) und was genau \emph{eine} Prü
Manche Klausuren (die im ersten Semester zum Beispiel) kann man auch 4 mal schreiben

2021-09-06 21:10 UTC, TomTomRixRix commented on studiengaenge/lehramt_info.tex
> +Die Bachelor-Arbeit wird im 50\%-Bachelor im ersten Hauptfach geschrieben. Falls du also beispielweise Englisch als erstes Hauptfach und Informatik als zweites Hauptfach hast, deine Bachelor-Arbeit a
Gendern: eine Dozentin; mach **sie**
Komma: verlangt, mach **sie**

2021-09-06 21:12 UTC, TomTomRixRix commented on wie-geht-studium/vorlesung_allgemein.tex
> +Im Gegensatz zur Schule gibt es an der Uni eine Reihe verschiedenartiger Veranstaltungen, in denen der Lehrstoff vermittelt werden soll. Im Wesentlichen sind das: Vorlesungen, Übungen, Seminare und P
Hier kann man vielleicht schon erklären, dass Bachelorseminare in der Mathematik als Teil der Bachelorarbeit was anderes sind als in der Informatik. Vielleicht in einer Fußnote oder so.

2021-09-06 21:23 UTC, TomTomRixRix commented on studiengaenge/bachelor_informatik.tex
>  Häufig habt ihr pro Prüfung zwei Versuche, es ist also nicht so schlimm, wenn beim ersten Versuch nicht bestanden habt. Einige Dozierende weichen aber von der Standardregelung ab, teilen euch dies al
Dieser Satz ist sehr missverständlich. Da Prüfung in der neuen PO == Klausur gilt, würde ich Folgendes vorschlagen: Häufig habt ihr pro Modul zwei Klausren, ... [...]. In manchen Grundlagenmodulen habt ihr sogar vier Klausuren, informiert euch also am ....

2021-09-06 21:24 UTC, TomTomRixRix commented on studiengaenge/bachelor_informatik.tex
> +\emph{Klausuranmeldungen sind immer verbindlich}. Überlegt euch also gut, ob ihr euch anmeldet. Solltet ihr euch sicher sein, die Klausur nicht zu bestehen, empfiehlt es sich, sich nicht anzumelden u
Ab der neuen PO zählen alle Module in die Abschlussnote, aber man kann zwei streichen, oder?

2021-09-06 21:27 UTC, TomTomRixRix requested changes
Bezüglich der neuen PO sollte man noch hinzufügen, dass es jetzt eine Maximalstudiendauer gibt. Ansonsten ist mir nichts relevantes mehr aufgefallen.

2021-09-06 21:28 UTC, TomTomRixRix commented on studiengaenge/bachelor_informatik.tex
> +Danach hört ihr im Modul \vl{Mathematische Grundlagen 3} eines der beiden Module \vl{Einführung in die Numerik} (\gls{Num0}) oder \vl{Einführung in die Wahrscheinlichkeitstheorie und Statistik} (\gls
Und laut Mail von Holger kann man auch Ana 2 als Wahlpflicht belegen. War mir vorher zwar nicht klar, aber mehr Wahlmöglichkeiten sind glaube ich nie verkehrt.

2021-09-06 21:33 UTC, TomTomRixRix commented
Mir ist gerade noch aufgefallen, dass im Abschnitt "Durchgefallen - Was tun?" im Kapitel "Studieren - wie geht das?" behauptet wird, das Prüfungen normalerweise aus Klausur und Nachklausur bestehen. Da sollte man eine Fußnote einfügen und sagen, dass dies in der Informatik inzwischen anders geregelt wird, man dafür aber mehr Prüfungsversuche hat.

2021-09-06 21:57 UTC, christian-heusel commented
Danke für deine Kommentare @TomTomRixRix ❤️

2021-09-14 19:17 UTC, TomTomRixRix approved these changes
Tippitoppi

2021-09-14 19:30 UTC, merged