Updated daten.tex (zu aktualisieren)
FachschaftMathPhysInfo/Ersti-Info pull request #392
Opened 2022-09-14 10:07 UTC by itsraeesa

2022-09-14 18:46 UTC, TomTomRixRix commented on zu_aktualisieren/daten.tex
> +\newcommand{\redaktionsschluss}{16.09.2021}
Müsste hier nicht 2022 stehen?

2022-09-15 08:50 UTC, nathapro requested changes

2022-09-15 08:50 UTC, nathapro commented on zu_aktualisieren/daten.tex
> +\newcommand{\prodekanphysik}{Andre Butz, Björn Malte Schäfer}
hier muss noch Fred Hamprecht dazu. Sie sind alle 3 Prodekan.

2022-09-15 08:50 UTC, nathapro commented on zu_aktualisieren/daten.tex
> -\newcommand{\prodekanphysikC}{J. Berges}
prodekanphysikC ist dann auch Hamprecht.

2022-09-15 08:50 UTC, nathapro commented on zu_aktualisieren/daten.tex
>  \newcommand{\prodekanphysikfotoA}{}
sind hier mit Absicht keine Bilder oder hast du keine gefunden?

2022-09-15 08:50 UTC, nathapro commented on zu_aktualisieren/daten.tex
>  \newcommand{\dozentvorkurs}{Herrn Berges und Herrn Thommes}
Den Vorkurs in der Physik machen dieses Jahr Eduard Thommes und Joerg Jaeckel

2022-09-15 08:50 UTC, nathapro commented on zu_aktualisieren/daten.tex
>  \newcommand{\studienberatungphysik}{Cornelis Dullemond und Tilman Enss}
Fachstudienberater:innen sind Tilman Enss, Stephanie Hansmann-Menzemer, Michael Hausmann, Selim Jochim und Andreas Just.

2022-09-15 08:50 UTC, nathapro commented on zu_aktualisieren/daten.tex
>  \newcommand{\prodekanphysikfotoA}{}
https://www.physik.uni-heidelberg.de/personen/?show=1&#start 
hier sind Bilder von alles Professoren hinterlegt. Wenn man auf die Personen klickt, sollte die Auflösung reichen.

2022-09-15 10:26 UTC, itsraeesa commented on zu_aktualisieren/daten.tex
> +\newcommand{\redaktionsschluss}{16.09.2021}
yup :)

2022-09-15 10:26 UTC, itsraeesa commented on zu_aktualisieren/daten.tex
>  \newcommand{\prodekanphysikfotoA}{}
Hier sind mit Absicht keine Bilder

2022-09-15 10:26 UTC, itsraeesa commented on zu_aktualisieren/daten.tex
>  \newcommand{\studienberatungphysik}{Cornelis Dullemond und Tilman Enss}
Vielen Dank für die Kommentare :)

2022-09-15 10:26 UTC, itsraeesa commented
Kommentare eingearbeitet... neues pull request gestartet (itsraeesa-patch5)

2022-09-15 10:26 UTC, closed without merging